export const hotelFeatures = [
    "24 Hour Reception",
    "Air Conditioned",
    "Allergy-Free Room Available",
    "ATM / Cash Machine",
    "Baby Listening/Monitoring",
    "Babysitting - Child Services",
    "Ballroom",
    "Banquet Facilities",
    "Bar / Lounge",
    "Bath / Hot Tub",
    "Bath Menu",
    "Bathrobes",
    "Bathtub/Shower Combination",
    "Beach (Direct Access)",
    "Beach (Nearby)",
    "Beach Soccer and Volleyball",
    "Beauty Salon",
    "Bedding/Pillow Choices",
    "Bicycle Rental",
    "Bidet",

    {id: 1, isChecked: false, serviceName: "Billiards"},
    {id: 1, isChecked: false, serviceName: "Boating"},
    {id: 1, isChecked: false, serviceName: "Body Treatments"},
    {id: 1, isChecked: false, serviceName: "Bowling Alley"},
    {id: 1, isChecked: false, serviceName: "Breakfast in the Room"},
    {id: 1, isChecked: false, serviceName: "Business Center"},
    {id: 1, isChecked: false, serviceName: "Cable - Satellite TV"},
    {id: 1, isChecked: false, serviceName: "Canoeing"},
    {id: 1, isChecked: false, serviceName: "Casino"},
    {id: 1, isChecked: false, serviceName: "CD Player"},
    {id: 1, isChecked: false, serviceName: "Cell phone/mobile rental"},
    {id: 1, isChecked: false, serviceName: "Ceremonies"},
    {id: 1, isChecked: false, serviceName: "Child Pool"},
    {id: 1, isChecked: false, serviceName: "Clay Pigeon Shooting"},
    {id: 1, isChecked: false, serviceName: "Coffee Or Tea Maker"},
    {id: 1, isChecked: false, serviceName: "Coffee Shop/Cafeteria"},
    {id: 1, isChecked: false, serviceName: "Complimentary Toiletries"},
    {id: 1, isChecked: false, serviceName: "Computer"},
    {id: 1, isChecked: false, serviceName: "Concierge"},
    {id: 1, isChecked: false, serviceName: "Conference Manager"},
    {id: 1, isChecked: false, serviceName: "Conference Room(s)"},
    {id: 1, isChecked: false, serviceName: "Connecting Rooms"},
    {id: 1, isChecked: false, serviceName: "Convention Center"},
    {id: 1, isChecked: false, serviceName: "Cots"},
    {id: 1, isChecked: false, serviceName: "Courier"},
    {id: 1, isChecked: false, serviceName: "Cricket Pitch"},
    {id: 1, isChecked: false, serviceName: "Currency Exchange"},
    {id: 1, isChecked: false, serviceName: "Custom event planning available"},
    {id: 1, isChecked: false, serviceName: "Cycling"},
    {id: 1, isChecked: false, serviceName: "Dart Board"},
    {id: 1, isChecked: false, serviceName: "Designated Smoking Area"},
    {id: 1, isChecked: false, serviceName: "Desk"},
    {id: 1, isChecked: false, serviceName: "Disabled Access"},
    {id: 1, isChecked: false, serviceName: "Disabled Accessible Rooms"},
    {id: 1, isChecked: false, serviceName: "Disabled Parking"},
    {id: 1, isChecked: false, serviceName: "Diving Centre"},
    {id: 1, isChecked: false, serviceName: "Dry Cleaning"},
    {id: 1, isChecked: false, serviceName: "DVD Player"},
    {id: 1, isChecked: false, serviceName: "Ecotours on Site"},
    {id: 1, isChecked: false, serviceName: "Elevator / Lift"},
    {id: 1, isChecked: false, serviceName: "En suite"},
    {id: 1, isChecked: false, serviceName: "Excursions"},
    {id: 1, isChecked: false, serviceName: "Executive Floor"},
    {id: 1, isChecked: false, serviceName: "Exhibit Space"},
    {id: 1, isChecked: false, serviceName: "Express Check-In/Check-Out"},
    {id: 1, isChecked: false, serviceName: "Facial Treatments"},
    {id: 1, isChecked: false, serviceName: "Facsimile"},
    {id: 1, isChecked: false, serviceName: "Family Room"},
    {id: 1, isChecked: false, serviceName: "Fine Dining"},
    {id: 1, isChecked: false, serviceName: "Fishing"},
    {id: 1, isChecked: false, serviceName: "Fitness Room Or Gym"},
    {id: 1, isChecked: false, serviceName: "Football Field"},
    {id: 1, isChecked: false, serviceName: "Full-service catering"},
    {id: 1, isChecked: false, serviceName: "Function Rooms"},
    {id: 1, isChecked: false, serviceName: "Games Available"},
    {id: 1, isChecked: false, serviceName: "Garden"},
    {id: 1, isChecked: false, serviceName: "Gay/Lesbian Friendly"},
    {id: 1, isChecked: false, serviceName: "Golf (miniature)"},
    {id: 1, isChecked: false, serviceName: "Golf Course"},
    {id: 1, isChecked: false, serviceName: "Golf Course (nearby)"},
    {id: 1, isChecked: false, serviceName: "Golf Course (on site)"},
    {id: 1, isChecked: false, serviceName: "Grab bars in bathroom"},
    {id: 1, isChecked: false, serviceName: "Hair Dryer"},
    {id: 1, isChecked: false, serviceName: "High-speed Internet is available at this hotel"},
    {id: 1, isChecked: false, serviceName: "Highchairs"},
    {id: 1, isChecked: false, serviceName: "Hiking"},
    {id: 1, isChecked: false, serviceName: "Horse Riding"},
    {id: 1, isChecked: false, serviceName: "Ice Machine"},
    {id: 1, isChecked: false, serviceName: "In Room Movies"},
    {id: 1, isChecked: false, serviceName: "Jacuzzi"},
    {id: 1, isChecked: false, serviceName: "Jet-Ski"},
    {id: 1, isChecked: false, serviceName: "Karaoke"},
    {id: 1, isChecked: false, serviceName: "Kayaking"},
    {id: 1, isChecked: false, serviceName: "Kids Club"},
    {id: 1, isChecked: false, serviceName: "Kitchenette"},
    {id: 1, isChecked: false, serviceName: "Knock Light (Hearing Impaired)"},
    {id: 1, isChecked: false, serviceName: "Lake"},
    {id: 1, isChecked: false, serviceName: "Laptop"},
    {id: 1, isChecked: false, serviceName: "Late check-out (subject to availability)"},

    {id: 1, isChecked: false, serviceName: "Laundry service"},
    {id: 1, isChecked: false, serviceName: "Luggage Storage"},
    {id: 1, isChecked: false, serviceName: "Massage"},
    {id: 1, isChecked: false, serviceName: "Massage Or Beauty Centre"},
    {id: 1, isChecked: false, serviceName: "Meeting Coordinator"},
    {id: 1, isChecked: false, serviceName: "Meeting Rooms"},
    {id: 1, isChecked: false, serviceName: "Microwave"},
    {id: 1, isChecked: false, serviceName: "Mini Bar"},
    {id: 1, isChecked: false, serviceName: "Mountain Climbing"},
    {id: 1, isChecked: false, serviceName: "Multilingual Staff"},
    {id: 1, isChecked: false, serviceName: "Nature Trail"},
    {id: 1, isChecked: false, serviceName: "News Stand"},
    {id: 1, isChecked: false, serviceName: "Nightclubs"},
    {id: 1, isChecked: false, serviceName: "Non-Smoking Rooms"},
    {id: 1, isChecked: false, serviceName: "Office Supplies"},
    {id: 1, isChecked: false, serviceName: "Outdoor heated pool"},
    {id: 1, isChecked: false, serviceName: "Packed Lunches"},
    {id: 1, isChecked: false, serviceName: "Parking is available"},
    {id: 1, isChecked: false, serviceName: "Personal Shopper Service"},
    {id: 1, isChecked: false, serviceName: "Pet Friendly"},
    {id: 1, isChecked: false, serviceName: "Photocopier"},
    {id: 1, isChecked: false, serviceName: "Picnic Area/Tables"},
    {id: 1, isChecked: false, serviceName: "Pillow Top Mattress"},
    {id: 1, isChecked: false, serviceName: "Playground"},
    {id: 1, isChecked: false, serviceName: "Pool Indoor"},
    {id: 1, isChecked: false, serviceName: "Pool Outdoor"},
    {id: 1, isChecked: false, serviceName: "Poolside Bar"},
    {id: 1, isChecked: false, serviceName: "Porters"},
    {id: 1, isChecked: false, serviceName: "Private Bathroom"},
    {id: 1, isChecked: false, serviceName: "Private beach"},
    {id: 1, isChecked: false, serviceName: "Private Toilet"},
    {id: 1, isChecked: false, serviceName: "Pub"},
    {id: 1, isChecked: false, serviceName: "Refrigerator"},
    {id: 1, isChecked: false, serviceName: "Restaurant"},
    {id: 1, isChecked: false, serviceName: "Rock Climbing"},
    {id: 1, isChecked: false, serviceName: "Room Service"},
    {id: 1, isChecked: false, serviceName: "Safe-Deposit Box"},
    {id: 1, isChecked: false, serviceName: "Salon"},
    {id: 1, isChecked: false, serviceName: "Sauna"},
    {id: 1, isChecked: false, serviceName: "Scooter/moped rentals are available at the hotel"},
    {id: 1, isChecked: false, serviceName: "Scuba Diving"},
    {id: 1, isChecked: false, serviceName: "Secretarial Service"},
    {id: 1, isChecked: false, serviceName: "Security Guard"},
    {id: 1, isChecked: false, serviceName: "Self Laundry"},
    {id: 1, isChecked: false, serviceName: "Shared Bathroom"},
    {id: 1, isChecked: false, serviceName: "Shoe Shine"},
    {id: 1, isChecked: false, serviceName: "Shops"},
    {id: 1, isChecked: false, serviceName: "Shops in Hotel"},
    {id: 1, isChecked: false, serviceName: "Shower"},
    {id: 1, isChecked: false, serviceName: "Skating Rink"},
    {id: 1, isChecked: false, serviceName: "Smoking Room"},
    {id: 1, isChecked: false, serviceName: "Souvenirs-Gift Shop"},
    {id: 1, isChecked: false, serviceName: "Spa & Wellness Centre"},
    {id: 1, isChecked: false, serviceName: "Spa bath / Jacuzzi"},
    {id: 1, isChecked: false, serviceName: "Squash Courts"},
    {id: 1, isChecked: false, serviceName: "Steam Bath"},
    {id: 1, isChecked: false, serviceName: "Supervised child care/activities"},
    {id: 1, isChecked: false, serviceName: "Surfing"},
    {id: 1, isChecked: false, serviceName: "Swimming pool"},
    {id: 1, isChecked: false, serviceName: "Tennis Courts"},
    {id: 1, isChecked: false, serviceName: "Tennis Courts (indoor)"},
    {id: 1, isChecked: false, serviceName: "The hotel has free parking"},
    {id: 1, isChecked: false, serviceName: "There is an airport shuttle that runs from the hotel"},
    {id: 1, isChecked: false, serviceName: "There is no parking on site"},
    {id: 1, isChecked: false, serviceName: "Ticket Service"},
    {id: 1, isChecked: false, serviceName: "Tour Desk"},
    {id: 1, isChecked: false, serviceName: "Towels"},
    {id: 1, isChecked: false, serviceName: "TV"},
    {id: 1, isChecked: false, serviceName: "Valet parking is offered at the hotel"},
    {id: 1, isChecked: false, serviceName: "Vending Machines"},
    {id: 1, isChecked: false, serviceName: "Video Conferencing"},
    {id: 1, isChecked: false, serviceName: "Volleyball"},
    {id: 1, isChecked: false, serviceName: "Wake-up Service"},
    {id: 1, isChecked: false, serviceName: "Water Activities"},
    {id: 1, isChecked: false, serviceName: "Water-skiing"},
    {id: 1, isChecked: false, serviceName: "Windsurfing"},
    {id: 1, isChecked: false, serviceName: "Wine Tasting"},
    {id: 1, isChecked: false, serviceName: "Wireless internet on site"},
    {id: 1, isChecked: false, serviceName: "Breakfast"},
    {id: 1, isChecked: false, serviceName: "Lunch"},
    {id: 1, isChecked: false, serviceName: "Dinner"},
    {id: 1, isChecked: false, serviceName: "Evening Snacks"},
]