export const leadMockData = [
    {
        "leadTitle": "Update lead new loves Ne edit",
        "paymentmode": "neft",
        "customerName": "Sampath",
        "getRequirementValue": "hotelStay",
        "noOfInfants": "1",
        "typeOfHoliday": "1",
        "dateANDtime": "",
        "pickUpPoint": "",
        "dropPoint": "",
        "noOfAdults": "2",
        "noOfKids": "1",
        "groupTourPackageList": "",
        "vehicleType": "",
        "noOfRooms": "8",
        "startDate": "2022-09-27",
        "endDate": "2022-09-28",
        "checkIN": "2022-09-27",
        "checkOUT": "2022-09-28",
        "distination": "Hyderabad",
        "noOfDays": "",
        "typeOfVisa": "",
        "coupleList": "Couple",
        "currencyType": "aud",
        "budgetForTrip": "10000",
        "requiredDocumentsList": "",
        "shortNote": "Short note 0",
        "selectLeadstatus": "completed",
        "leadGeneratedNo": "HB22090956",
        "leadCreatedDate": "September 27th 2022, 9:56:03 pm",
        "serviceAirfare": true,
        "serviceInvernalTransport": true,
        "serviceHotelStay": true,
        "serviceSightseeing": true,
        "serviceVisaFees": true,
        "serviceGovtTax": true,
        "serviceSurcharge": true,
        "serviceCruiseStay": true,
        "serviceFreeGoodies": true,
        "serviceAllMeals": true,
        "servicePassportFrees": true,
        "serviceBreakfast": true,
        "serviceTourManager": true,
        "serviceMAP": true,
        "id": 28
    },
    {
        "leadTitle": "Updated Lead Title",
        "paymentmode": "",
        "customerName": "Roshan",
        "getRequirementValue": "groupTourPackage",
        "noOfInfants": "2",
        "typeOfHoliday": "2",
        "dateANDtime": "",
        "pickUpPoint": "",
        "dropPoint": "",
        "noOfAdults": "1",
        "noOfKids": "2",
        "groupTourPackageList": "Group List",
        "vehicleType": "",
        "noOfRooms": "",
        "startDate": "2022-09-28",
        "endDate": "2022-09-28",
        "checkIN": "",
        "checkOUT": "",
        "distination": "Hyderabad",
        "noOfDays": "",
        "typeOfVisa": "",
        "coupleList": "Couple",
        "currencyType": "eur",
        "budgetForTrip": "10000",
        "requiredDocumentsList": "",
        "shortNote": "Short note",
        "selectLeadstatus": "confirmed",
        "leadGeneratedNo": "HB22090938",
        "leadCreatedDate": "September 27th 2022, 9:38:31 pm",
        "serviceAirfare": true,
        "serviceInvernalTransport": true,
        "serviceHotelStay": "",
        "serviceSightseeing": "",
        "serviceVisaFees": "",
        "serviceGovtTax": "",
        "serviceSurcharge": "",
        "serviceCruiseStay": "",
        "serviceFreeGoodies": "",
        "serviceAllMeals": "",
        "servicePassportFrees": true,
        "serviceBreakfast": "",
        "serviceTourManager": "",
        "serviceMAP": false,
        "id": 27
    },
    {
        "leadTitle": "Conditional Title",
        "paymentmode": "Cash",
        "customerName": "Roshan",
        "getRequirementValue": "fitTourPackage",
        "noOfInfants": "1",
        "typeOfHoliday": "1",
        "dateANDtime": "",
        "pickUpPoint": "",
        "dropPoint": "",
        "noOfAdults": "2",
        "noOfKids": "2",
        "groupTourPackageList": "",
        "vehicleType": "",
        "noOfRooms": "",
        "startDate": "2022-09-22",
        "endDate": "2022-09-29",
        "checkIN": "",
        "checkOUT": "",
        "distination": "Bangalroe",
        "noOfDays": "",
        "typeOfVisa": "",
        "coupleList": "Couple",
        "currencyType": "aud",
        "budgetForTrip": "2999",
        "requiredDocumentsList": "",
        "shortNote": "",
        "selectLeadstatus": "inProgress",
        "leadGeneratedNo": "HB22090909",
        "leadCreatedDate": "September 27th 2022, 9:09:06 pm",
        "serviceAirfare": true,
        "serviceInvernalTransport": "",
        "serviceHotelStay": "",
        "serviceSightseeing": "",
        "serviceVisaFees": true,
        "serviceGovtTax": "",
        "serviceSurcharge": "",
        "serviceCruiseStay": "",
        "serviceFreeGoodies": true,
        "serviceAllMeals": "",
        "servicePassportFrees": "",
        "serviceBreakfast": "",
        "serviceTourManager": true,
        "serviceMAP": "",
        "id": 26
    },
    {
        "leadTitle": "NEwt lead",
        "paymentmode": "",
        "customerName": "Roshan",
        "getRequirementValue": "forex",
        "noOfInfants": "",
        "typeOfHoliday": "",
        "dateANDtime": "",
        "pickUpPoint": "",
        "dropPoint": "",
        "noOfAdults": "",
        "noOfKids": "",
        "groupTourPackageList": "",
        "vehicleType": "",
        "noOfRooms": "",
        "startDate": "",
        "endDate": "",
        "checkIN": "",
        "checkOUT": "",
        "distination": "",
        "noOfDays": "",
        "typeOfVisa": "",
        "coupleList": "",
        "currencyType": "usd",
        "budgetForTrip": "100000000099",
        "requiredDocumentsList": "",
        "shortNote": "Check box selecsdted alll",
        "selectLeadstatus": "new",
        "leadGeneratedNo": "HB22091118",
        "leadCreatedDate": "September 26th 2022, 11:18:51 am",
        "serviceAirfare": true,
        "serviceInvernalTransport": true,
        "serviceHotelStay": true,
        "serviceSightseeing": true,
        "serviceVisaFees": true,
        "serviceGovtTax": true,
        "serviceSurcharge": true,
        "serviceCruiseStay": true,
        "serviceFreeGoodies": true,
        "serviceAllMeals": true,
        "servicePassportFrees": true,
        "serviceBreakfast": true,
        "serviceTourManager": true,
        "serviceMAP": true,
        "id": 25
    },
    {
        "leadTitle": "check box uncheck",
        "paymentmode": "",
        "customerName": "P",
        "getRequirementValue": "groupTourPackage",
        "noOfInfants": "",
        "typeOfHoliday": "",
        "dateANDtime": "",
        "pickUpPoint": "",
        "dropPoint": "",
        "noOfAdults": "",
        "noOfKids": "",
        "groupTourPackageList": "",
        "vehicleType": "",
        "noOfRooms": "",
        "startDate": "2022-09-21",
        "endDate": "2022-09-27",
        "checkIN": "",
        "checkOUT": "",
        "distination": "",
        "noOfDays": "",
        "typeOfVisa": "",
        "coupleList": "",
        "currencyType": "",
        "budgetForTrip": "",
        "requiredDocumentsList": "",
        "shortNote": "check box uncheked",
        "selectLeadstatus": "canceled",
        "leadGeneratedNo": "HB22091053",
        "leadCreatedDate": "September 26th 2022, 10:53:51 am",
        "serviceAirfare": "",
        "id": 24
    },
    {
        "leadTitle": "Checkbox",
        "paymentmode": "",
        "customerName": "Akram",
        "getRequirementValue": "fitTourPackage",
        "noOfInfants": "",
        "typeOfHoliday": "",
        "dateANDtime": "",
        "pickUpPoint": "",
        "dropPoint": "",
        "noOfAdults": "",
        "noOfKids": "",
        "groupTourPackageList": "",
        "vehicleType": "",
        "noOfRooms": "",
        "startDate": "2022-09-17",
        "endDate": "2022-09-29",
        "checkIN": "",
        "checkOUT": "",
        "distination": "",
        "noOfDays": "",
        "typeOfVisa": "",
        "coupleList": "",
        "currencyType": "",
        "budgetForTrip": "",
        "requiredDocumentsList": "",
        "shortNote": "checkbox testing",
        "selectLeadstatus": "new",
        "leadGeneratedNo": "HB22091051",
        "leadCreatedDate": "September 26th 2022, 10:51:50 am",
        "serviceAirfare": true,
        "id": 23
    },
    {
        "leadTitle": "ROshan journy",
        "paymentmode": "",
        "customerName": "Akram",
        "getRequirementValue": "groupTourPackage",
        "noOfInfants": "11",
        "typeOfHoliday": "1",
        "dateANDtime": "",
        "pickUpPoint": "",
        "dropPoint": "",
        "noOfAdults": "33",
        "noOfKids": "11",
        "groupTourPackageList": "List package",
        "vehicleType": "",
        "noOfRooms": "",
        "startDate": "2022-09-14",
        "endDate": "2022-09-29",
        "checkIN": "",
        "checkOUT": "",
        "distination": "Nandyal",
        "noOfDays": "",
        "typeOfVisa": "",
        "coupleList": "Couple",
        "currencyType": "usd",
        "budgetForTrip": "2000",
        "requiredDocumentsList": "",
        "shortNote": "NOte hsote",
        "selectLeadstatus": "new",
        "leadGeneratedNo": "HB22091031",
        "leadCreatedDate": "September 26th 2022, 10:31:43 am",
        "id": 22
    },
    {
        "leadTitle": "Updated Lead",
        "paymentmode": "Cash",
        "customerName": "Roshan",
        "getRequirementValue": "fitTourPackage",
        "noOfInfants": "2",
        "typeOfHoliday": "1",
        "dateANDtime": "",
        "pickUpPoint": "",
        "dropPoint": "",
        "noOfAdults": "2",
        "noOfKids": "1",
        "groupTourPackageList": "",
        "vehicleType": "",
        "noOfRooms": "",
        "startDate": "2022-10-05",
        "endDate": "2022-09-08",
        "checkIN": "",
        "checkOUT": "",
        "distination": "Maldives",
        "noOfDays": "",
        "typeOfVisa": "",
        "coupleList": "PerPerson",
        "currencyType": "dpr",
        "budgetForTrip": "1000",
        "requiredDocumentsList": "",
        "shortNote": "Short note",
        "selectLeadstatus": "new",
        "leadGeneratedNo": "HB22091020",
        "leadCreatedDate": "September 26th 2022, 10:20:43 am",
        "id": 21
    },
    {
        "leadTitle": "Honeymoon journey",
        "paymentmode": "online",
        "customerName": "Roshan",
        "getRequirementValue": "fitTourPackage",
        "noOfInfants": "3",
        "typeOfHoliday": "2",
        "dateANDtime": "2022-09-22T10:02",
        "pickUpPoint": "Hyd",
        "dropPoint": "BLR",
        "noOfAdults": "3",
        "noOfKids": "1",
        "groupTourPackageList": "Group list",
        "vehicleType": "1",
        "noOfRooms": "2",
        "startDate": "2022-09-20",
        "endDate": "2022-09-27",
        "checkIN": "2022-09-30",
        "checkOUT": "2022-10-05",
        "distination": "Honeymoon",
        "noOfDays": "333",
        "typeOfVisa": "Visiting Vis",
        "coupleList": "PerPerson",
        "currencyType": "aud",
        "budgetForTrip": "1000",
        "requiredDocumentsList": "",
        "shortNote": "My short note",
        "selectLeadstatus": "inProgress",
        "leadGeneratedNo": "HB22090801",
        "leadCreatedDate": "September 24th 2022, 8:01:52 pm",
        "id": 20
    },
    {
        "leadTitle": "Sample lead",
        "paymentmode": "",
        "customerName": "Akram",
        "getRequirementValue": "carService",
        "noOfInfants": "",
        "typeOfHoliday": "",
        "dateANDtime": "",
        "pickUpPoint": "",
        "dropPoint": "",
        "noOfAdults": "",
        "noOfKids": "",
        "groupTourPackageList": "",
        "vehicleType": "",
        "noOfRooms": "",
        "startDate": "",
        "endDate": "",
        "checkIN": "",
        "checkOUT": "",
        "distination": "",
        "noOfDays": "",
        "typeOfVisa": "",
        "coupleList": "",
        "currencyType": "",
        "budgetForTrip": "",
        "requiredDocumentsList": "",
        "shortNote": "",
        "selectLeadstatus": "canceled",
        "leadGeneratedNo": "HB22090730",
        "leadCreatedDate": "September 24th 2022, 7:30:03 pm",
        "id": 19
    },
    {
        "leadTitle": "This is new lead",
        "paymentmode": "",
        "customerName": "Roshan",
        "getRequirementValue": "fitTourPackage",
        "noOfInfants": "10",
        "typeOfHoliday": "1",
        "dateANDtime": "2022-09-23T07:20",
        "pickUpPoint": "Bangalore",
        "dropPoint": "Hyderabad",
        "noOfAdults": "3",
        "noOfKids": "2",
        "groupTourPackageList": "Group Tour List package",
        "vehicleType": "1",
        "noOfRooms": "2",
        "startDate": "2022-09-24",
        "endDate": "2022-09-29",
        "checkIN": "2022-09-30",
        "checkOUT": "2022-09-28",
        "distination": "Honeymoon",
        "noOfDays": "3",
        "typeOfVisa": "Visiting Visa",
        "coupleList": "Couple",
        "currencyType": "inr",
        "budgetForTrip": "199919",
        "requiredDocumentsList": "",
        "shortNote": "Short Note goes here",
        "selectLeadstatus": "new",
        "leadGeneratedNo": "HB22090717",
        "leadCreatedDate": "September 24th 2022, 7:17:46 pm",
        "id": 18
    }
]